[workspace]
resolver = "2"
members = [
    "examples/rust-kitchen-sink",
    "examples/rust-simple",
    "headless-terminal",
    "terminal-games-cli",
    "terminal-games-sdk",
    "terminal-games-server",
    "terminal-games",
]
