[package]
name = "terminal-games"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
futures = "0.3.31"
rand_core = { version = "0.6.4" }
russh = "0.55.0"
tracing-log = "0.2"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
wasmtime = "40"
wasmtime-wasi = { version = "40", default-features = false, features = ["p1"] }
yansi = { version = "1.0.1", features = ["hyperlink"] }
unicode-width = "0.2"
strip-ansi-escapes = "0.2.1"
libsql = "0.9.29"
tokio-rustls = { version = "0.26.4", default-features = false, features = [
    "tls12",
] }
rustls = "0.23.35"
rustls-pki-types = "1.0.0"
webpki-roots = "1.0.4"
headless-terminal = { path = "../headless-terminal" }
smallvec = "1"
serde = { version = "1.0", features = ["derive"] }
postcard = { version = "1", default-features = false }
tokio-util = { version = "0.7", features = ["codec", "rt"] }
bytes = "1"
hex = "0.4"
async-trait = "0.1"
libc = "0.2"
