[package]
name = "terminal-games"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
tokio = { version = "1.48.0", features = ["full"] }
wasmtime = "39.0.1"
wasmtime-wasi = "39.0.1"
