[package]
name = "terminal-games"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
futures = "0.3.31"
rand_core = { version = "0.6.4" }
russh = "0.55.0"
tracing-log = "0.2"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
wasmtime = "39.0.1"
wasmtime-wasi = "39.0.1"
yansi = { version = "1.0.1", features = ["hyperlink"] }
unicode-width = "0.2.2"
strip-ansi-escapes = "0.2.1"
libsql = "0.9.29"
