[package]
name = "terminal-games-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.29", default-features = false }
terminput = "0.5"
tokio = { version = "1", features = ["time"], optional = true }

[features]
network = ["dep:tokio"]
